import type { Config } from 'tailwindcss';

const config: Config = {
  darkMode: ['class'],
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      borderRadius: {
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
        xl: "0.75rem",
        full: "9999px"
      },
      colors: {
        "surface-dim": "#cbdbf5",
        "primary-fixed-dim": "#c3c0ff",
        "on-primary-container": "#dad7ff",
        "surface": "#f8f9ff",
        "on-tertiary": "#ffffff",
        "on-secondary-fixed": "#25005a",
        "surface-bright": "#f8f9ff",
        "on-background": "#0b1c30",
        "landing-primary": "#3525cd",
        "on-surface-variant": "#464555",
        "on-secondary-container": "#fffbff",
        "on-primary-fixed": "#0f0069",
        "surface-tint": "#4d44e3",
        "surface-container-highest": "#d3e4fe",
        "surface-container-lowest": "#ffffff",
        "outline": "#777587",
        "on-primary": "#ffffff",
        "secondary-container": "#8a4cfc",
        "tertiary-fixed-dim": "#ffb695",
        "on-secondary": "#ffffff",
        "surface-container-low": "#eff4ff",
        "on-tertiary-fixed-variant": "#7b2f00",
        "on-surface": "#0b1c30",
        "landing-secondary": "#712ae2",
        "on-error": "#ffffff",
        "secondary-fixed": "#eaddff",
        "inverse-on-surface": "#eaf1ff",
        "tertiary-container": "#a44100",
        "surface-container-high": "#dce9ff",
        "primary-container": "#4f46e5",
        "on-primary-fixed-variant": "#3323cc",
        "tertiary-fixed": "#ffdbcc",
        "surface-variant": "#d3e4fe",
        "inverse-surface": "#213145",
        "outline-variant": "#c7c4d8",
        "primary-fixed": "#e2dfff",
        "on-tertiary-fixed": "#351000",
        "on-tertiary-container": "#ffd2be",
        "on-secondary-fixed-variant": "#5a00c6",
        "error": "#ba1a1a",
        "landing-background": "#f8f9ff",
        "tertiary": "#7e3000",
        "secondary-fixed-dim": "#d2bbff",
        "on-error-container": "#93000a",
        "inverse-primary": "#c3c0ff",
        "error-container": "#ffdad6",
        "surface-container": "#e5eeff",
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        card: {
          DEFAULT: 'hsl(var(--card))',
          foreground: 'hsl(var(--card-foreground))',
        },
        popover: {
          DEFAULT: 'hsl(var(--popover))',
          foreground: 'hsl(var(--popover-foreground))',
        },
        primary: {
          DEFAULT: 'hsl(var(--primary))',
          foreground: 'hsl(var(--primary-foreground))',
        },
        secondary: {
          DEFAULT: 'hsl(var(--secondary))',
          foreground: 'hsl(var(--secondary-foreground))',
        },
        muted: {
          DEFAULT: 'hsl(var(--muted))',
          foreground: 'hsl(var(--muted-foreground))',
        },
        accent: {
          DEFAULT: 'hsl(var(--accent))',
          foreground: 'hsl(var(--accent-foreground))',
        },
        destructive: {
          DEFAULT: 'hsl(var(--destructive))',
          foreground: 'hsl(var(--destructive-foreground))',
        },
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
      },
      spacing: {
        "xl": "32px",
        "margin-mobile": "16px",
        "lg": "24px",
        "sm": "12px",
        "xs": "4px",
        "base": "8px",
        "md": "16px",
        "gutter": "24px",
        "container-max": "1280px"
      },
      fontFamily: {
        "headline-md": ["Geist", "sans-serif"],
        "headline-lg": ["Geist", "sans-serif"],
        "label-md": ["JetBrains Mono", "monospace"],
        "body-md": ["Geist", "sans-serif"],
        "display": ["Geist", "sans-serif"],
        "headline-lg-mobile": ["Geist", "sans-serif"],
        "body-lg": ["Geist", "sans-serif"]
      },
      fontSize: {
        "headline-md": ["20px", {"lineHeight": "28px", "letterSpacing": "-0.01em", "fontWeight": "500"}],
        "headline-lg": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.02em", "fontWeight": "600"}],
        "label-md": ["12px", {"lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "500"}],
        "body-md": ["14px", {"lineHeight": "20px", "letterSpacing": "0em", "fontWeight": "400"}],
        "display": ["48px", {"lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "600"}],
        "headline-lg-mobile": ["24px", {"lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
        "body-lg": ["16px", {"lineHeight": "24px", "letterSpacing": "0em", "fontWeight": "400"}]
      },
    },
  },
  plugins: [require('tailwindcss-animate')],
};

export default config;
